### ISSUE TITLE
TOC in docs

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread-packages/hello#5]
需要进入docs目录时就给出直观的信息列表出来，包括首页的链接也应该指向过来。

**Comment by armink** [comment]
现在是这样的效果 https://github.com/RT-Thread-packages/hello/tree/master/docs

**Comment by BernardXiong** [comment]
我是觉得当进入docs目录时，是否可以看起来更像一份完整的文档？

**Comment by armink** [comment]
Markdown 不支持引用其他 md 源文件，你的意思做成类似这样的吗？



# 文档

## 软件包地址

- https://github.com/RT-Thread-packages/hello

## 版本信息

请查看：[version.md](version.md)  

## 详细介绍

请查看：[introduction.md](introduction.md)

## 工作原理

请查看：[principle.md](principle.md)

**Comment by BernardXiong** [comment]
好像确实没什么更好的办法，毕竟markdown不能支持包含文件。后续就按现有的给出一份列表的方式也就可以了。

**Comment by armink** [comment]
好的，那 issue 先关闭了
